### ISSUE TITLE
yaml lint over selected files

### ISSUE THREAD

**Issue by jgato** [jgato/ztp-prevalidate#1]
the script yaml lint validation should happen only over the files that are going to be, later, managed by GitOps. Therfore, reading the kustomization file to see what files are included. 

Example:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  #- sno3-e.yaml
  - sno4.yaml
  - sno3-e-4-10.yaml
  #- sno4-e-4-10.yaml
  #- sno5-e-4-9.yaml
  - el8k-ztp-1-3node.yaml
  #- el8k-ztp-1-3node-ipv6.yaml
  #- el8k-ztp-1-standard-ipv6.yaml
  #- el8k-ztp-1-standard-ipv6-4-8.yaml
  #- el8k-ztp-1-standard-4-8.yaml
  #- el8k-ztp-1-standard.yaml
  #- sno4-e-4-10-no-sctp.yaml
  - sno5-e-4-9-only-sctp.yaml
  - sno-b7-e-4-10-ipv4.yaml
  - sno-b8-e-4-10-ipv4.yaml
```
